Name: Configure_Recipe_Editor_RT
Type: ProjectFolder
Children:
- Name: BranchingEnabled
  Type: BaseDataVariableType
  DataType: Boolean
  Value: false
- Name: PasswordPolicy
  Type: PasswordPolicy
  Children:
  - Name: MaximumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: EnforcePasswordHistory
    Type: PropertyType
    DataType: Byte
    Value: 1
  - Name: MinimumPasswordAge
    Type: PropertyType
    DataType: UInt16
    Value: 0
  - Name: MinimumPasswordLength
    Type: PropertyType
    DataType: Byte
    Value: 8
- Name: Locales
  Type: BaseDataVariableType
  DataType: String
  ValueRank: OneDimension
  ArrayDimensions: [0]
  Value: ["en-US"]
- Name: LocaleFallbackList
  Type: BaseDataVariableType
  DataType: String
  ValueRank: OneDimension
  ArrayDimensions: [0]
  Value: ["en-US"]
- File: UI/UI.yaml
- File: Model/Model.yaml
- File: Converters/Converters.yaml
- File: Alarms/Alarms.yaml
- File: Recipes/Recipes.yaml
- File: Loggers/Loggers.yaml
- File: DataStores/DataStores.yaml
- File: Reports/Reports.yaml
- File: 'OPC-UA/OPC-UA.yaml'
- File: CommDrivers/CommDrivers.yaml
- File: NetLogic/NetLogic.yaml
- File: Security/Security.yaml
- File: Translations/Translations.yaml
- File: Retentivity/Retentivity.yaml
- Name: DefaultUserFolder
  Type: NodePointer
  DataType: NodeId
  Value: {"IdType":2,"Id":"da30c6c75b7aacb1f3608d52cebd3f96","Namespace":7}
  Children:
  - Name: Kind
    Type: PropertyType
    DataType: NodeId
    Value: {"Id":61}
- Name: RecipeSchema1
  Type: Alias
  DataType: NodeId
  Value: {"IdType":2,"Id":"2a2241f1449b8aa2aa5edca1495dc366","Namespace":7}
  Children:
  - Name: Kind
    Type: PropertyType
    DataType: NodeId
    Value: {"IdType":2,"Id":"80584ce97616c3ad402a855b506f5d4e","Namespace":7}
